version: "3"

services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  ganache-cli:
    image: trufflesuite/ganache-cli
    ports:
      - 8545:8545

  owner:
    image: owner
    environment:
      - PRODUCTION=True
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_URL=database
      - DATABASE_NAME=courier_service_database
      - BLOCKCHAIN_URL=http://ganache-cli:8545
    ports:
      - 5000:5000

  courier:
    image: courier
    environment:
      - PRODUCTION=True
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_URL=database
      - DATABASE_NAME=courier_service_database
      - BLOCKCHAIN_URL=http://ganache-cli:8545
    ports:
      - 5001:5000

  customer:
    image: customer
    environment:
      - PRODUCTION=True
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_URL=database
      - DATABASE_NAME=courier_service_database
      - BLOCKCHAIN_URL=http://ganache-cli:8545
    ports:
      - 5002:5000
