version: "3"

volumes:
  database_volume:

networks:
  adminer_network:
  users_network:

services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      # - ./data:/var/lib/mysql
      - database_volume:/var/lib/mysql
    networks:
      - adminer_network
      - users_network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - adminer_network

  users:
    image: users:v4
    environment:
      - DATABASE_URL=database
    ports:
      - 5000:5000
    networks:
      - users_network
